spring:
  application:
    name: versionamientov2
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/
          tenant-id: e5372bf0-c5e3-4286-887c-79069f209c1f
